@startuml


note "init_backend_system." as INIT


INIT .. Kiran::MenuSkeleton
INIT .. Kiran::AppManager
INIT .. Kiran::WindowManager
INIT .. Kiran::WorkspaceManager

Kiran::MenuSkeleton o--> Kiran::MenuNew
Kiran::MenuSkeleton o--> Kiran::MenuUsage
Kiran::MenuSkeleton o--> Kiran::MenuCategory
Kiran::MenuSkeleton o--> Kiran::MenuFavorite
Kiran::MenuSkeleton o--> Kiran::MenuSearch


Kiran::MenuCategory --> Kiran::Category
Kiran::MenuCategory ..> Kiran::CategoryReader
Kiran::MenuCategory ..> Kiran::CategoryWriter
Kiran::Category --> Kiran::CategoryNode
Kiran::CategoryReader --> Kiran::CategoryNode
Kiran::CategoryWriter --> Kiran::CategoryNode


Kiran::AppManager o..> Kiran::App
Kiran::WindowManager o..> Kiran::Window
Kiran::WorkspaceManager o..> Kiran::Workspace

@enduml