variables:
  EXTRA_DNF_REPOS: |
                   [KIRAN-UI-2.6]
                   name=KIRAN-UI-2.6
                   gpgcheck=0
                   baseurl=http://10.20.20.71/kojifiles/repos/KY3.5-1-KiranUI-2.6-build/latest/x86_64/

  RPM_BUILD_REQUIRES: 'mate-panel-devel mate-desktop-devel gettext libwnck3-devel glib2-2.68.1-10.kb1.ky3 gtk3-devel gtkmm30-devel cairomm-devel libX11-devel libxcb-devel gtk-update-icon-cache kiran-panel-devel kiran-log-gtk3-devel libdbusmenu-devel fmt-devel json-glib-devel kiran-cc-daemon-devel'
  WORK_BRANCHES: '2.5 2.6'

include:
  - project: 'os/ks-devops'
    ref: main
    file:
      - '/entrypoint/develop/cmake.yml'
